################ English language ##################
[fr]
languageName = "Fr"
languageCode = "fr-fr"
contentDir = "content/french"
weight = 1

[en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 2
