############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About"
url = "/about"
weight = 2

[[main]]
name = "Blog"
url = "/blog"
weight = 3

[[main]]
weight = 4
name = "Pages"

[[main]]
parent = "Pages"
name = "Contact"
url = "/contact"

[[main]]
parent = "Pages"
name = "Categories"
url = "/categories"

# footer menu
[[footer]]
name = "About"
url = "/about"
weight = 1

[[footer]]
name = "Blog"
url = "/blog"
weight = 2
